template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "sars1236"
__REPO__ = "lang-srs"
__UND2C__ = "srs"
__UNDEFINED__ = "Sarsi"
__UND__ = "srs"
