template = "https://github.com/giellalt/template-lang-und"
rev_id = 340
template_sha = "1186578fa79468b8b3349a52ce4880edc3ce8803"

[replacements]
__GLOTTOLOG_ID__ = "sars1236"
__REPO__ = "lang-srs"
__UND2C__ = "srs"
__UNDEFINED__ = "Sarsi"
__UND__ = "srs"
