template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "sars1236"
__REPO__ = "lang-srs"
__UND2C__ = "srs"
__UNDEFINED__ = "Sarsi"
__UND__ = "srs"
