[package]
name = "srs"
human_name = "Sarsi"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.srs]
filename = "srs-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-srs"
platform = "windows"
uuid = "72764F3E-D461-42D8-BAFE-BBF3CF93D7BD"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.srs"
package = "speller-srs"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-srs-mso"
platform = "windows"
uuid = "3598DFFC-3AD4-4D8F-82FD-8D2CD69B5AE0"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-srs"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
